apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: tierlist-gateway
  namespace: default
spec:
  selector:
    istio: ingressgateway  # Cible l'Ingress Gateway d'Istio
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
