apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tierlist-backend-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: tierlist.local
      http:
        paths:
          - path: /api/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: tierlist-backend-service
                port:
                  number: 3001
