apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:6.0  # MongoDB version 6.0
          ports:
            - containerPort: 27017  # Default MongoDB port
          env:
            - name: MONGO_INITDB_DATABASE
              value: mastertier  # Initializes the DB with 'mastertier' database
          volumeMounts:
            - name: mongodb-storage  # Mounts the volume inside the container
              mountPath: /data/db    # MongoDB default data path
      volumes:
        - name: mongodb-storage
          persistentVolumeClaim:
            claimName: mongodb-pvc  # Binds the pod to the PVC for persistent storage
